version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build

  build-backend:
    docker:
            - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Back-end build
          command: |
             cd backend
             npm install 
             npm run build

            

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
